{{- $servicePort := .Values.service.externalPort -}}
{{- $fullname := include "fullname" . -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullname }}-frontend-svc
              servicePort: {{ $servicePort }}
          - path: /solar
            backend:
              serviceName: {{ $fullname }}-api-svc
              servicePort: {{ $servicePort }}

    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
        {{- range $host := .Values.ingress.hosts }}
        - {{ $host }}
        {{- end }}
      secretName: {{ .Values.ingress.certName }}
  {{- end -}}
