version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: solar
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: solar