---
imgrepo: appcfg.azurecr.io/
imagePullPolicy: Allways
deploymentName: development
service:
  externalPort: 80

image: app-config
imageTag: 27
imagePullPolicy: Always

api:
  internalPort: 3001
  replicas: 1

frontend:
  externalPort: 8080
  internalPort: 80
  replicas: 1

ingress:
  enabled: true
  hosts:
  - solar-deploy-1.nearform.net
  annotations:
    kubernetes.io/ingress.class: contour


apiImage: api-image:deploy-1
frontendImage: frontend-image:deploy-1
