---
imgrepo: pathfinders.azurecr.io/
imagePullPolicy: Allways
deploymentName: development
service:
  externalPort: 80

image: app-config
imageTag: 27
imagePullPolicy: Always

api:
  internalPort: 3001
  replicas: 1
  dbhost: pathfinders-pg.postgres.database.azure.com
  dbssl: "true"
  dbport: 5432
  dbuser: solar
  db: solar

frontend:
  externalPort: 8080
  internalPort: 80
  replicas: 1

ingress:
  enabled: true
  hosts:
  - app-config-dev.nearform.net
  annotations:
    kubernetes.io/tls-acme: 'false'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
  - hosts:
    - app-config-dev.nearform.net
    secretName: app-config-tls

apiImage: api-image:latest
frontendImage: frontend-image:latest
